[2024-05-12T15:43:18.847+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T15:43:18.892+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_mlops_dag.load manual__2024-05-12T15:35:55.995449+00:00 [queued]>
[2024-05-12T15:43:18.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_mlops_dag.load manual__2024-05-12T15:35:55.995449+00:00 [queued]>
[2024-05-12T15:43:18.910+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-12T15:43:18.954+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-12 15:35:55.995449+00:00
[2024-05-12T15:43:18.964+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'simple_mlops_dag', 'load', 'manual__2024-05-12T15:35:55.995449+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpl271700b']
[2024-05-12T15:43:18.968+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask load
[2024-05-12T15:43:18.974+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=42) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-12T15:43:18.975+0000] {standard_task_runner.py:63} INFO - Started process 51 to run task
[2024-05-12T15:43:19.085+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_mlops_dag.load manual__2024-05-12T15:35:55.995449+00:00 [running]> on host 885b0ae9b1ba
[2024-05-12T15:43:19.275+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='simple_mlops_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T15:35:55.995449+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T15:35:55.995449+00:00'
[2024-05-12T15:43:19.278+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T15:43:19.355+0000] {logging_mixin.py:188} INFO - -----------Storing data------------
[2024-05-12T15:43:19.357+0000] {logging_mixin.py:188} INFO - Error storing data: [Errno 13] Permission denied: 'dvc'
[2024-05-12T15:43:19.358+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-12T15:43:19.359+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T15:43:19.391+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_mlops_dag, task_id=load, run_id=manual__2024-05-12T15:35:55.995449+00:00, execution_date=20240512T153555, start_date=20240512T154318, end_date=20240512T154319
[2024-05-12T15:43:19.512+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-12T15:43:19.568+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T15:43:19.571+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
