[2024-05-12T16:00:27.675+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T16:00:27.740+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_mlops_dag.load manual__2024-05-12T15:59:51.347570+00:00 [queued]>
[2024-05-12T16:00:27.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_mlops_dag.load manual__2024-05-12T15:59:51.347570+00:00 [queued]>
[2024-05-12T16:00:27.763+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-12T16:00:27.815+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-12 15:59:51.347570+00:00
[2024-05-12T16:00:27.837+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'simple_mlops_dag', 'load', 'manual__2024-05-12T15:59:51.347570+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmph9idsj4f']
[2024-05-12T16:00:27.840+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask load
[2024-05-12T16:00:27.848+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-12T16:00:27.850+0000] {standard_task_runner.py:63} INFO - Started process 78 to run task
[2024-05-12T16:00:27.960+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_mlops_dag.load manual__2024-05-12T15:59:51.347570+00:00 [running]> on host cf26b4c5269f
[2024-05-12T16:00:28.159+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='simple_mlops_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T15:59:51.347570+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T15:59:51.347570+00:00'
[2024-05-12T16:00:28.161+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T16:00:28.185+0000] {logging_mixin.py:188} INFO - -----------Storing data------------
[2024-05-12T16:00:28.188+0000] {logging_mixin.py:188} INFO - Error storing data: [Errno 13] Permission denied: 'dvc'
[2024-05-12T16:00:28.188+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-12T16:00:28.190+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T16:00:28.205+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_mlops_dag, task_id=load, run_id=manual__2024-05-12T15:59:51.347570+00:00, execution_date=20240512T155951, start_date=20240512T160027, end_date=20240512T160028
[2024-05-12T16:00:28.266+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-12T16:00:28.292+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T16:00:28.295+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
