[2024-05-12T16:01:49.395+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T16:01:49.443+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_mlops_dag.load manual__2024-05-12T16:01:09.991283+00:00 [queued]>
[2024-05-12T16:01:49.471+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_mlops_dag.load manual__2024-05-12T16:01:09.991283+00:00 [queued]>
[2024-05-12T16:01:49.472+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-12T16:01:49.597+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-12 16:01:09.991283+00:00
[2024-05-12T16:01:49.612+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'simple_mlops_dag', 'load', 'manual__2024-05-12T16:01:09.991283+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpnk5zcuw3']
[2024-05-12T16:01:49.615+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask load
[2024-05-12T16:01:49.623+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-12T16:01:49.625+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2024-05-12T16:01:49.788+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_mlops_dag.load manual__2024-05-12T16:01:09.991283+00:00 [running]> on host cf26b4c5269f
[2024-05-12T16:01:50.005+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='simple_mlops_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T16:01:09.991283+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T16:01:09.991283+00:00'
[2024-05-12T16:01:50.007+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T16:01:50.024+0000] {logging_mixin.py:188} INFO - -----------Storing data------------
[2024-05-12T16:01:50.026+0000] {logging_mixin.py:188} INFO - Error storing data: [Errno 13] Permission denied: 'dvc'
[2024-05-12T16:01:50.028+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-12T16:01:50.029+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T16:01:50.044+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=simple_mlops_dag, task_id=load, run_id=manual__2024-05-12T16:01:09.991283+00:00, execution_date=20240512T160109, start_date=20240512T160149, end_date=20240512T160150
[2024-05-12T16:01:50.122+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-12T16:01:50.147+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T16:01:50.149+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
